services:
  w3r5l3y-ssh:
    build: .
    container_name: w3r5l3y-ssh
    ports:
      - "23234:23234"
    environment:
      SSH_ADDR: "0.0.0.0:23234"
      SSH_HOST_KEY_PATH: "/data/keys/ssh_host_ed25519_key"
      SSH_THEME: "violet"
    volumes:
      - w3r5l3y_ssh_data:/data
    restart: unless-stopped

volumes:
  w3r5l3y_ssh_data:
